### PR TITLE
Create folders

### PR DESCRIPTION
**Pull request by AdamKaczkowski**
Create folders: src, docs, tests

### CODE REVIEW

**Review by s22811 — APPROVED** [review]

**Comment by s17580** [comment]
looks like everything is ok, I approve.

**Review by s17580 — APPROVED** [review]

**Comment by s20454userpjatk** [comment]
Looks ok

**Review by s20454userpjatk — APPROVED** [review]

**Comment by s20454userpjatk** [comment]
Looks, fine

**Review by AdamKaczkowski — COMMENTED** [review]
Accept

**Pull request merged**
